print("Reading a content from the file:\n")
file=open("myfile.txt","r")
data=(file.read())
print("The content of the file is:\n")
print(data)
a=data
c=a.split()
print("The splitted sentence is :\n")
print(c)
res=set(c)
print("The repeated words in given sentence are\n")
print(res)
print("number of times codes occur in given file")
occurrences=data.count("codes")
print(occurrences)
print("number of times welcome word occur in given file")
occurrences1=data.count("welcome")
print(occurrences1)
print("number of times python word  occur in given file")
occurrences2=data.count("python")
print(occurrences2)

